# Generated by Django 5.0.6 on 2024-10-30 03:41

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='id',
            field=hashid_field.field.HashidAutoField(
                alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                min_length=7,
                prefix='',
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='id',
            field=hashid_field.field.HashidAutoField(
                alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                min_length=7,
                prefix='',
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
