# Generated by Django 5.0.6 on 2024-10-30 04:28

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0008_alter_reportrun_id_alter_reporttemplate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='template_data',
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='file',
            field=models.FileField(default='null', upload_to=common.storages.UniqueFilePathGenerator('documents')),
            preserve_default=False,
        ),
    ]
