# Generated by Django 5.0.6 on 2024-10-30 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0010_remove_reporttemplate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='file',
            field=models.FileField(
                default='null',
                upload_to='',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'pptx', 'xlsx'])],
            ),
            preserve_default=False,
        ),
    ]
